services:
  ml-model:
    build: 
      context: ./ml-model
      dockerfile: Dockerfile
    container_name: capstone-ml-model
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: capstone-backend
    depends_on:
      ml-model:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      ML_MODEL_URL: "http://ml-model:5000"
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3001
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: capstone-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: "http://backend:3001"
      NODE_ENV: ${NODE_ENV:-production}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
