version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: capstone-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ml-service:
    build: ./ml-service
    container_name: capstone-ml-service
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://root:example@mongo:27017/mydb?authSource=admin"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: capstone-backend
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb://root:example@mongo:27017/mydb?authSource=admin"
      ML_SERVICE_URL: "http://ml-service:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: capstone-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mongodb_data: