version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: capstone-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-mydb}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  ml-model:
    build: ./ml-model
    container_name: capstone-ml-model
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASSWORD:-example}@mongo:27017/${MONGO_DB:-mydb}?authSource=admin"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: capstone-backend
    depends_on:
      mongo:
        condition: service_healthy
      ml-model:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASSWORD:-example}@mongo:27017/${MONGO_DB:-mydb}?authSource=admin"
      ML_model_URL: "http://ml-model:5000"
      NODE_ENV: ${NODE_ENV:-production}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: capstone-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    restart: unless-stopped

volumes:
  mongodb_data: